openapi: 3.0.2
info:
  description: "Search twitter data by hashtag and username"
  version: "1.0.0"
  title: "Twitter Scraper"
  contact:
    email: "burakdonmezxyz@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /hashtags/{hashtag}/:
    get:
      operationId: hashtag
      description: Get tweets by hashtags. Returns tweets by pages. Shows 30 tweets by page as default. Page limit can be changed by using "limit" parameter.
      parameters:
      - name: hashtag
        in: path
        required: true
        description: 'Hashtag value to retrieve tweets'
        schema:
          type: string
      - name: limit
        in: query
        description: Number of tweets to show in a page.
        required: false
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tweet'
          description: 'Successful'
      tags:
      - hashtags
  /users/{username}/:
    get:
      operationId: username
      description: Get tweets by username. Returns tweets by pages. Shows 30 tweets by page as default. Page limit can be changed by using "limit" parameter.
      parameters:
      - name: username
        in: path
        required: true
        description: 'Username value to retrieve tweets'
        schema:
          type: string
      - name: limit
        in: query
        description: Number of tweets to show in a page.
        required: false
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tweet'
          description: ''
      tags:
      - users
components:
  schemas:
    Tweet:
      type: object
      properties:
        account:
          type: object
          properties:
            fullname:
              type: string
              maxLength: 255
            href:
              type: string
              readOnly: true
            id:
              type: integer
          required:
          - fullname
          - id
        date:
          type: string
          format: date-time
        hashtags:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                maxLength: 255
            required:
            - name
        likes:
          type: integer
        replies:
          type: integer
        retweets:
          type: integer
        text:
          type: string
          maxLength: 280
      required:
      - account
      - date
      - hashtags
      - likes
      - replies
      - retweets
      - text
